### ISSUE TITLE
ServerDriven library Implemented

### ISSUE THREAD

**Issue by flash159483** [soma-lighthouse/FE-lingo-swap#5]
## 설명
- [x] Network Interceptor
- [x] connect API to UI
- [x] network handler added 
- [x] JSON Deserializer for server driven
- [x]  Simple test UI added
- [x] Rich Text Implemented
- [x] UiState added 
## TODO (Optional)
- [x] Rich text not Implementing properly
